<a href="https://colab.research.google.com/github/alwiemuflich/Belajar_Machine_Learning/blob/main/Belajar_Petama_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
path_="/content/drive/My Drive/Machine_Learning/Persentase Perokok RI.csv"
dataset=pd.read_csv(path_)
dataset

                Provinsi   2015   2016
0                   ACEH  29.82  28.16
1         SUMATERA UTARA  29.15  27.88
2         SUMATERA BARAT  32.41  30.59
3                   RIAU  31.21  29.61
4                  JAMBI  30.82  29.18
5       SUMATERA SELATAN  33.13  31.57
6               BENGKULU  33.68  33.15
7                LAMPUNG  34.12  33.39
8   KEP. BANGKA BELITUNG  30.70  29.32
9              KEP. RIAU  29.18  29.25
10           DKI JAKARTA  27.31  26.42
11            JAWA BARAT  33.82  32.67
12           JAWA TENGAH  28.57  27.19
13         DI YOGYAKARTA  24.12  23.11
14            JAWA TIMUR  29.03  28.16
15                BANTEN  32.95  31.64
16                  BALI  22.96  21.62
17   NUSA TENGGARA BARAT  31.60  30.88
18   NUSA TENGGARA TIMUR  25.47  24.91
19      KALIMANTAN BARAT  29.35  28.09
20     KALIMANTAN TENGAH  30.53  29.21
21    KALIMANTAN SELATAN  25.76  25.34
22      KALIMANTAN TIMUR  25.59  25.23
23      KALIMANTAN UTARA  28.61  28.38
24        SULAWESI UTARA  29.31  29.23
25       SULAWESI TENGAH  32.56  31.88
26      SULAWESI SELATAN  25.49  25.13
27     SULAWESI TENGGARA  28.49  27.60
28             GORONTALO  33.93  31.71
29        SULAWESI BARAT  28.29  27.36
30                MALUKU  27.19  25.68
31          MALUKU UTARA  31.14  30.23
32           PAPUA BARAT  29.28  26.18
33                 PAPUA  26.67  24.04